
from unittest import TestCase


class TestFailure(TestCase):

    def test_failure(self):
        return 1